//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wmaud_webapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACFI_articulo
    {
        public decimal art_codigo { get; set; }
        public string art_nombre { get; set; }
        public Nullable<decimal> cat_codigo { get; set; }
        public Nullable<decimal> art_precio { get; set; }
    }
}
