//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wmaud_webapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACFI_categoria
    {
        public decimal cat_codigo { get; set; }
        public string cat_nombre { get; set; }
        public string cat_visible { get; set; }
    }
}
