//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wmaud_webapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACFI_equipos
    {
        public string equipo_codigo { get; set; }
        public Nullable<decimal> alm_codigo { get; set; }
        public Nullable<decimal> equipo_valor { get; set; }
        public Nullable<decimal> art_codigo { get; set; }
        public string fecha_ingreso { get; set; }
        public Nullable<decimal> usu_codigo { get; set; }
        public Nullable<System.DateTime> fecha_auditoria { get; set; }
        public string estado_auditoria { get; set; }
    }
}
