//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wmaud_webapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACFI_almacen
    {
        public decimal alm_codigo { get; set; }
        public string alm_nombre { get; set; }
        public Nullable<decimal> alm_estado { get; set; }
        public string fecha_modificacion { get; set; }
        public string fecha_revision { get; set; }
        public Nullable<decimal> monto_revision { get; set; }
        public Nullable<decimal> tipoalm_codigo { get; set; }
    }
}
