//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wmaud_webapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPTURAS_AUDITORIA
    {
        public int CORRELATIVO { get; set; }
        public string TAG_ERROR { get; set; }
        public string BARRA_ERROR { get; set; }
        public string OBSERVACION { get; set; }
        public string NOMBRE_FOTO { get; set; }
        public string TAG_CORREGIDO { get; set; }
        public string CODIGO_LOCAL { get; set; }
        public string USER_ERROR { get; set; }
    }
}
