//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wmaud_webapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_AUDITORIA
    {
        public string NOMBRE_USUARIO { get; set; }
        public string FECHA_PROCESO { get; set; }
        public string TURNO { get; set; }
        public string CODIGO_LOCAL { get; set; }
        public string RECEPCION { get; set; }
    }
}
